### ISSUE TITLE
Make Host Names Configurable

### ISSUE THREAD

**Issue by mamurak** [FNNDSC/pfcon#74]
The host names of the third party services (swift, pman, pfioh) are currently hardcoded. Since these names are generally dependent on the particular runtime environment, changing them should not require rebuilding the service. (Side note: The current host names are not compliant with Kubernetes.)

AC: Please make the host names of third party services configurable using environment variables.

Note: For compatibility sake, it makes sense to make the host names settings optional, using the current host names as default values.

**Comment by mamurak** [comment]
Go/no-go decision pending.

**Comment by junaruga** [comment]
@mamurak Why is this ticket in the "pending to do" status? What blocks it?

**Comment by mamurak** [comment]
@junaruga It was unclear whether adapting the current `pfcon` makes sense as it's currently being rewritten. However, I'm preparing a pull request right now as the adaptation is rather small.

**Comment by junaruga** [comment]
@mamurak OK, thanks for the work!

**Comment by jennydaman** [comment]
I don't know how much would be out of scope, but it would be important for `swift_service` and the remote service names themselves configurable.

https://github.com/FNNDSC/pfcon/blob/201a9e326ec4d692b5db99b727cc8eec536b3d2b/pfcon/pfcon.py#L85

We are moving torward a vision of "one pfcon per remote" (cc @jbernal0019)

**Comment by jbernal0019** [comment]
Fixed by the new Flask-based `pfcon` .
